package tdns

import (
	"context"
	"testing"

	core "github.com/johanix/tdns/v2/core"
	"github.com/miekg/dns"
)

// An empty RRset is a caller error, and SignRRset has always had the check for
// it. The five-minute-validity warning was added ABOVE that check and reads
// rrset.RRs[0], which turned the error return into an index-out-of-range panic
// in a server goroutine -- taking the whole daemon down (#565).
func TestSignRRsetRefusesAnEmptyRRsetRatherThanPanicking(t *testing.T) {
	zd, kdb, _ := rolledZone(t)
	_ = kdb

	for _, tc := range []struct {
		name  string
		rrset core.RRset
	}{
		{"no RRs at all", core.RRset{Name: zd.ZoneName, RRtype: dns.TypeCSYNC}},
		{"an empty RRs slice", core.RRset{Name: zd.ZoneName, RRtype: dns.TypeCSYNC, RRs: []dns.RR{}}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			// A panic here fails the test rather than the process, which is the
			// only difference between this and the field report.
			rrset := tc.rrset
			signed, err := zd.SignRRset(&rrset, zd.ZoneName, nil, true, nil)
			if err == nil {
				t.Fatal("signing an empty RRset reported success")
			}
			if signed {
				t.Error("reported that it signed an RRset with no records")
			}
		})
	}
}

// A key generated by the key-state worker is staged as PUBLISHED, and
// FetchZoneDnskeysSql serves published keys -- so it enters the served DNSKEY
// RRset immediately, under an RRSIG made over the set without it. That is not a
// stale signature but a bogus zone, and everything delegated beneath it fails to
// validate too (#566).
//
// The two state transitions either side of this in KeyStateWorker both call
// triggerResign. Adding a key to the RRset needs it exactly as much.
func TestGeneratingAStandbyKeyTriggersAResign(t *testing.T) {
	zd, kdb, _ := rolledZone(t)

	prev := Conf.Internal.ResignQ
	q := make(chan ResignRequest, 4)
	Conf.Internal.ResignQ = q
	t.Cleanup(func() { Conf.Internal.ResignQ = prev })
	conf := &Config{}
	conf.Internal.ResignQ = q

	Zones.Set(zd.ZoneName, zd)
	t.Cleanup(func() { Zones.Remove(zd.ZoneName) })

	// No standby ZSK exists, so this generates one.
	maintainStandbyKeysForType(context.Background(), conf, kdb, zd.ZoneName, dns.ED25519, "ZSK", 256, 1, false)

	select {
	case req := <-q:
		if req.Zd == nil || req.Zd.ZoneName != zd.ZoneName {
			t.Fatalf("re-sign queued for the wrong zone: %+v", req.Zd)
		}
		if req.Reason != ResignKeyStateChanged {
			t.Errorf("reason %v, want %v: a key entering the DNSKEY RRset is a key-state"+
				" change, and only that reason replaces signatures", req.Reason, ResignKeyStateChanged)
		}
	default:
		t.Fatal("no re-sign was triggered, so the zone keeps serving a DNSKEY RRset that its" +
			" RRSIG does not cover -- bogus to every validator until something else happens" +
			" to re-sign it")
	}
}

// And it must not fire when nothing was generated, or every pass of the worker
// would queue a re-sign for every zone.
func TestNoStandbyKeyGeneratedMeansNoResign(t *testing.T) {
	zd, kdb, _ := rolledZone(t)

	prev := Conf.Internal.ResignQ
	q := make(chan ResignRequest, 4)
	Conf.Internal.ResignQ = q
	t.Cleanup(func() { Conf.Internal.ResignQ = prev })
	conf := &Config{}
	conf.Internal.ResignQ = q

	Zones.Set(zd.ZoneName, zd)
	t.Cleanup(func() { Zones.Remove(zd.ZoneName) })

	// Ask for zero standbys: the count is already satisfied, nothing is
	// generated, and the served RRset does not change.
	maintainStandbyKeysForType(context.Background(), conf, kdb, zd.ZoneName, dns.ED25519, "ZSK", 256, 0, false)

	select {
	case req := <-q:
		t.Fatalf("queued a re-sign for %s with no key generated", req.Zd.ZoneName)
	default:
	}
}

// noResignQ is for the callers that are not testing the trigger. triggerResign
// returns immediately on a nil ResignQ, so the key-maintenance behaviour under
// test is unaffected.
func noResignQ() *Config { return &Config{} }
