/*
 * Copyright (c) 2025 Johan Stenstam, johan.stenstam@internetstiftelsen.se
 */
package tdns

import (
	"context"
	"fmt"
	"log"
	"time"

	core "github.com/johanix/tdns/v2/core"
	"github.com/miekg/dns"
	"github.com/spf13/viper"
)

type SynchedDataUpdate struct {
	Zone              ZoneName
	AgentId           AgentId
	UpdateType        string // "local" or "remote"
	Update            *ZoneUpdate
	OriginatingDistID string // Distribution ID from the originating agent (for remote updates)
	Force             bool   // Bypass dedup check (always send even if RR already present)
	SkipCombiner      bool   // Don't send to combiner (e.g. local DNSKEY changes — signer adds its own)
	// Response chan *SynchedDataResponse
	Response chan *AgentMsgResponse
}

type SynchedDataResponse struct {
	Zone    ZoneName
	AgentId AgentId
	Time    time.Time
	Msg     string
	// RfiType     string
	RfiResponse RfiData
	Error       bool
	ErrorMsg    string
}

type SynchedDataCmd struct {
	Cmd      string
	Zone     ZoneName
	Response chan *SynchedDataCmdResponse
}

type SynchedDataCmdResponse struct {
	Cmd      string
	Msg      string
	Error    bool
	ErrorMsg string
	Zone     ZoneName
	ZDR      map[ZoneName]map[AgentId]map[uint16][]TrackedRRInfo
}

type ZoneUpdate struct {
	Zone    ZoneName
	AgentId AgentId
	RRsets  map[uint16]core.RRset // remote updates are only per RRset (i.e. full replace)
	RRs     []dns.RR              // local updates can be per RR
}

type AgentId string

func (id AgentId) String() string {
	return string(id)
}

type ZoneName string

func (name ZoneName) String() string {
	return string(name)
}

type ZoneDataRepo struct {
	// Repo map[ZoneName]ZoneRepo // map[zonename]ZoneRepo
	Repo core.ConcurrentMap[ZoneName, *AgentRepo] // map[zonename]ZoneRepo

	// Tracking stores per-RR lifecycle state parallel to Repo.
	// Accessed only from the SynchedDataEngine goroutine.
	// Structure: zone → agentId → rrtype → TrackedRRset
	Tracking map[ZoneName]map[AgentId]map[uint16]*TrackedRRset

	// PendingRemoteConfirms maps a combiner distID (generated by this remote agent)
	// to the originating agent's distID and sender identity. When the combiner confirms
	// the remote agent's enqueue, this mapping is used to send the final confirmation
	// back to the originating agent with the correct originating distID.
	PendingRemoteConfirms map[string]*PendingRemoteConfirmation
}

// PendingRemoteConfirmation tracks the relationship between a combiner distID
// (generated locally on the remote agent) and the originating agent's distID/identity.
type PendingRemoteConfirmation struct {
	OriginatingDistID string
	OriginatingSender string
	Zone              ZoneName
}

// RemoteConfirmationDetail carries per-RR confirmation detail to send back
// to the originating agent after the remote agent's combiner confirms.
type RemoteConfirmationDetail struct {
	OriginatingDistID string
	OriginatingSender string
	Zone              ZoneName
	Status            string
	Message           string
	AppliedRecords    []string
	RemovedRecords    []string
	RejectedItems     []RejectedItemInfo
	Truncated         bool
}
type AgentRepo struct {
	// Data map[AgentId]OwnerData // map[agentid]data
	Data core.ConcurrentMap[AgentId, *OwnerData] // map[agentid]data
}

func (ar *AgentRepo) Get(agentId AgentId) (*OwnerData, bool) {
	// dump.P(ar.Data)
	return ar.Data.Get(agentId)
}

func (ar *AgentRepo) Set(agentId AgentId, ownerData *OwnerData) {
	ar.Data.Set(agentId, ownerData)
}

func NewAgentRepo() (*AgentRepo, error) {
	return &AgentRepo{
		Data: core.NewStringer[AgentId, *OwnerData](),
	}, nil
}

func NewZoneDataRepo() (*ZoneDataRepo, error) {
	return &ZoneDataRepo{
		Repo:     core.NewStringer[ZoneName, *AgentRepo](),
		Tracking: make(map[ZoneName]map[AgentId]map[uint16]*TrackedRRset),
	}, nil
}

func (zdr *ZoneDataRepo) Get(zone ZoneName) (*AgentRepo, bool) {
	return zdr.Repo.Get(zone)
}

func (zdr *ZoneDataRepo) Set(zone ZoneName, agentRepo *AgentRepo) {
	zdr.Repo.Set(zone, agentRepo)
}

// RRState represents the lifecycle state of a tracked RR.
type RRState uint8

const (
	RRStatePending        RRState = iota // Sent to combiner, awaiting confirmation
	RRStateAccepted                      // Combiner accepted
	RRStateRejected                      // Combiner rejected (see Reason)
	RRStatePendingRemoval                // Delete sent to combiner, awaiting confirmation
	RRStateRemoved                       // Combiner confirmed removal (audit trail)
)

func (s RRState) String() string {
	switch s {
	case RRStatePending:
		return "pending"
	case RRStateAccepted:
		return "accepted"
	case RRStateRejected:
		return "rejected"
	case RRStatePendingRemoval:
		return "pending-removal"
	case RRStateRemoved:
		return "removed"
	default:
		return "unknown"
	}
}

// RRConfirmation records a single recipient's confirmation status for a tracked RR.
type RRConfirmation struct {
	Status    string    `json:"status"`           // "accepted", "rejected", "removed", "pending"
	Reason    string    `json:"reason,omitempty"` // rejection reason
	Timestamp time.Time `json:"timestamp"`
}

// TrackedRR wraps a dns.RR with lifecycle state for combiner confirmation tracking.
type TrackedRR struct {
	RR                 dns.RR
	State              RRState
	Reason             string // Rejection reason (empty unless rejected)
	DistributionID     string // Last distribution this RR was part of
	UpdatedAt          time.Time
	Confirmations      map[string]RRConfirmation // recipientID → per-recipient status
	ExpectedRecipients []string                  // Who must confirm before state transitions to accepted
}

// TrackedRRset holds a set of tracked RRs for a single RRtype.
type TrackedRRset struct {
	Tracked []TrackedRR
}

// ConfirmationDetail carries per-RR confirmation feedback from the combiner
// through to the SynchedDataEngine.
type ConfirmationDetail struct {
	DistributionID string
	Zone           ZoneName
	Source         string // Identifies the confirming peer (combiner ID or agent ID)
	Status         string // "ok", "partial", "error"
	Message        string
	AppliedRecords []string
	RemovedRecords []string // RR strings confirmed as removed by combiner
	RejectedItems  []RejectedItemInfo
	Truncated      bool
	Timestamp      time.Time
}

// RejectedItemInfo describes an RR rejected by the combiner.
type RejectedItemInfo struct {
	Record string
	Reason string
}

// TrackedRRInfo is the JSON-serializable form for dump output.
type TrackedRRInfo struct {
	RR             string                    `json:"rr"`
	State          string                    `json:"state"`
	Reason         string                    `json:"reason,omitempty"`
	DistributionID string                    `json:"distribution_id"`
	UpdatedAt      string                    `json:"updated_at"`
	Confirmations  map[string]RRConfirmation `json:"confirmations,omitempty"`
}

// SynchedDataEngine is a component that updates the combiner with new information
// received from the agents that are sharing zones with us.
func (conf *Config) SynchedDataEngine(ctx context.Context, msgQs *MsgQs) {
	SDupdateQ := msgQs.SynchedDataUpdate
	SDcmdQ := msgQs.SynchedDataCmd

	var synchedDataUpdate *SynchedDataUpdate
	var ok bool

	if !viper.GetBool("syncheddataengine.active") {
		log.Printf("SynchedDataEngine is NOT active. No updates will be sent to the combiner.")
		for {
			select {
			case <-ctx.Done():
				log.Printf("SynchedDataEngine: context cancelled")
				return
			case synchedDataUpdate, ok = <-SDupdateQ:
				if !ok {
					log.Printf("SynchedDataEngine: synchedDataUpdate channel closed")
					return
				}
				log.Printf("SynchedDataEngine: NOT active, but received an update: %+v", synchedDataUpdate)
				// Send error response back to avoid timeout
				if synchedDataUpdate.Response != nil {
					synchedDataUpdate.Response <- &AgentMsgResponse{
						Error:    true,
						ErrorMsg: "SynchedDataEngine is not active",
						Msg:      "syncheddataengine.active is set to false in configuration",
					}
				}
			}
			continue
		}
	} else {
		log.Printf("SynchedDataEngine: Starting")
	}

	// XXX: Set up communication with the combiner

	zdr, err := NewZoneDataRepo()
	if err != nil {
		log.Printf("SynchedDataEngine: Failed to create zone data repo: %v", err)
		return
	}

	conf.Internal.ZoneDataRepo = zdr

	log.Printf("*** SynchedDataEngine starting ***")

	for {
		select {
		case <-ctx.Done():
			log.Printf("SynchedDataEngine: context cancelled")
			return
			// stopch removed; ctx.Done() handles shutdown

		case synchedDataUpdate = <-SDupdateQ:
			var change bool
			switch synchedDataUpdate.UpdateType {
			case "local":
				log.Printf("SynchedDataEngine: Received local update: %+v", synchedDataUpdate)

				// 1. Evaluate the update for applicability (valid zone, etc)
				// 2. Evaluate the update according to policy.

				// Prepare a response in case there is a response channel.
				// resp := SynchedDataResponse{
				resp := AgentMsgResponse{
					Zone:    synchedDataUpdate.Zone,
					AgentId: synchedDataUpdate.AgentId,
				}

				// agent_policy.go: EvaluateUpdate()
				ok, msg, err := zdr.EvaluateUpdate(synchedDataUpdate)
				if err != nil {
					log.Printf("SynchedDataEngine: Failed to evaluate update: %v", err)
					continue
				}

				if !ok {
					log.Printf("SynchedDataEngine: Update not applicable, skipping")
					resp.Error = true
					resp.ErrorMsg = msg
				} else {
					resp.Msg = msg
					// 3. Add the update to the agent data repo.
					// agent_policy.go: ProcessUpdate()
					change, msg, err = zdr.ProcessUpdate(synchedDataUpdate)
					if err != nil {
						log.Printf("SynchedDataEngine: Failed to add update to agent data repo: %v", err)
						resp.Error = true
						resp.ErrorMsg = err.Error()
						resp.Msg = msg
					}
					if change {
						tm := conf.Internal.TransportManager
						if tm != nil && synchedDataUpdate.Update != nil {
							// Generate a single shared distID for combiner + all agents
							distID := GenerateQueueDistributionID()

							// Build the expected recipients list for confirmation tracking
							recipients := tm.GetDistributionRecipients(synchedDataUpdate.Zone, synchedDataUpdate.SkipCombiner)

							if synchedDataUpdate.SkipCombiner {
								log.Printf("SynchedDataEngine: Update applied, enqueuing for remote agents only (SkipCombiner)")
							} else {
								log.Printf("SynchedDataEngine: Update applied, enqueuing for combiner and remote agents")
								// Enqueue for combiner (reliable delivery with retry)
								_, err := tm.EnqueueForCombiner(synchedDataUpdate.Zone, synchedDataUpdate.Update, distID)
								if err != nil {
									log.Printf("SynchedDataEngine: Failed to enqueue for combiner: %v", err)
									resp.Error = true
									resp.ErrorMsg = fmt.Sprintf("Combiner enqueue error: %v", err)
								} else {
									// Mark all RRs in this update as pending with the distribution ID
									zdr.MarkRRsPending(synchedDataUpdate.Zone, synchedDataUpdate.AgentId, synchedDataUpdate.Update, distID, recipients)
								}
							}

							// Enqueue for all remote agents in this zone (same distID)
							if err := tm.EnqueueForZoneAgents(synchedDataUpdate.Zone, synchedDataUpdate.Update, distID); err != nil {
								log.Printf("SynchedDataEngine: Failed to enqueue for zone agents: %v", err)
								if resp.ErrorMsg != "" {
									resp.ErrorMsg += "; " + fmt.Sprintf("Agent enqueue error: %v", err)
								} else {
									resp.Error = true
									resp.ErrorMsg = fmt.Sprintf("Agent enqueue error: %v", err)
								}
							}

							if !resp.Error {
								if synchedDataUpdate.SkipCombiner {
									resp.Msg = "Local update applied, sync enqueued for remote agents"
								} else {
									resp.Msg = "Local update applied, sync enqueued for combiner and zone agents"
								}
							}
						} else if tm == nil {
							log.Printf("SynchedDataEngine: TransportManager not available, cannot enqueue sync messages")
							resp.Error = true
							resp.ErrorMsg = "TransportManager not available"
						}
					}
				}

				if synchedDataUpdate.Response != nil {
					select {
					case synchedDataUpdate.Response <- &resp:
					default:
						log.Printf("SynchedDataEngine: Response channel blocked, skipping response")
					}
				}
			case "remote":
				log.Printf("SynchedDataEngine: Received remote update: %+v", synchedDataUpdate)

				// 1. Evaluate the update for applicability (valid zone, etc)
				// 2. Evaluate the update according to policy.

				// Prepare a response in case there is a response channel.
				// resp := SynchedDataResponse{
				resp := AgentMsgResponse{
					Zone:    synchedDataUpdate.Zone,
					AgentId: synchedDataUpdate.AgentId,
				}

				// agent_policy.go: EvaluateUpdate()
				ok, msg, err := zdr.EvaluateUpdate(synchedDataUpdate)
				if err != nil {
					log.Printf("SynchedDataEngine: Failed to evaluate update: %v", err)
					continue
				}

				if !ok {
					log.Printf("SynchedDataEngine: Update not applicable, skipping")
					resp.Error = true
					resp.ErrorMsg = msg
				} else {
					resp.Msg = msg

					// 3. Add the update to the agent data repo.
					// agent_policy.go: ProcessUpdate()
					change, msg, err = zdr.ProcessUpdate(synchedDataUpdate)
					if err != nil {
						log.Printf("SynchedDataEngine: Failed to add update to agent data repo: %v", err)
						resp.Error = true
						resp.ErrorMsg = err.Error()
					}
					resp.Msg = msg
					if change {
						log.Printf("SynchedDataEngine: Update applied, remote data has changed, enqueuing for combiner")

						tm := conf.Internal.TransportManager
						if tm != nil && synchedDataUpdate.Update != nil {
							// Remote update: only enqueue for combiner (not back to agents)
							distID, err := tm.EnqueueForCombiner(synchedDataUpdate.Zone, synchedDataUpdate.Update, "")
							if err != nil {
								log.Printf("SynchedDataEngine: Failed to enqueue for combiner: %v", err)
								resp.Error = true
								resp.ErrorMsg = fmt.Sprintf("Combiner enqueue error: %v", err)
							} else {
								// Remote update: only the combiner is the expected recipient
								var remoteRecipients []string
								if tm.combinerID != "" {
									remoteRecipients = []string{string(tm.combinerID)}
								}
								zdr.MarkRRsPending(synchedDataUpdate.Zone, synchedDataUpdate.AgentId, synchedDataUpdate.Update, distID, remoteRecipients)
								resp.Msg = "Remote update applied, sync enqueued for combiner"

								// Track mapping from our combiner distID to the originating agent's distID
								// so we can send the final confirmation back when our combiner confirms.
								if synchedDataUpdate.OriginatingDistID != "" {
									if zdr.PendingRemoteConfirms == nil {
										zdr.PendingRemoteConfirms = make(map[string]*PendingRemoteConfirmation)
									}
									zdr.PendingRemoteConfirms[distID] = &PendingRemoteConfirmation{
										OriginatingDistID: synchedDataUpdate.OriginatingDistID,
										OriginatingSender: string(synchedDataUpdate.AgentId),
										Zone:              synchedDataUpdate.Zone,
									}
									log.Printf("SynchedDataEngine: Tracking remote confirm: combiner distID %s → originating distID %s from %s",
										distID, synchedDataUpdate.OriginatingDistID, synchedDataUpdate.AgentId)
								}
							}
						} else if tm == nil {
							log.Printf("SynchedDataEngine: TransportManager not available, cannot enqueue sync messages")
							resp.Error = true
							resp.ErrorMsg = "TransportManager not available"
						}
					}
				}
				if synchedDataUpdate.Response != nil {
					select {
					case synchedDataUpdate.Response <- &resp:
					default:
						log.Printf("SynchedDataEngine: Response channel blocked, skipping response")
					}
				}
			}

		case sdcmd := <-SDcmdQ:
			log.Printf("SynchedDataEngine: Received command: %+v", sdcmd)
			switch sdcmd.Cmd {
			case "dump-zonedatarepo":

				if sdcmd.Response == nil {
					log.Printf("SynchedDataEngine: Command has no response channel, skipping")
					continue
				}
				log.Printf("SynchedDataEngine: Dumping zone data repo")

				dumpData := make(map[ZoneName]map[AgentId]map[uint16][]TrackedRRInfo)

				// dumpZoneAgent extracts RRs and their tracking state for a zone/agent.
				// Includes both active RRs from the repo and tracking-only entries
				// (e.g. Removed RRs that are no longer in the active repo but kept for audit).
				dumpZoneAgent := func(zone ZoneName, agentId AgentId, ownerData *OwnerData) map[uint16][]TrackedRRInfo {
					rrsetData := make(map[uint16][]TrackedRRInfo)

					// Collect active RRs from the repo with their tracking state
					for rrtype, rrset := range ownerData.RRtypes.data.Items() {
						var infos []TrackedRRInfo
						activeRRs := make(map[string]bool)
						for _, rr := range rrset.RRs {
							rrStr := rr.String()
							activeRRs[rrStr] = true
							info := TrackedRRInfo{
								RR:    rrStr,
								State: "unknown",
							}
							// Look up tracking state
							if zdr.Tracking[zone] != nil &&
								zdr.Tracking[zone][agentId] != nil &&
								zdr.Tracking[zone][agentId][rrtype] != nil {
								for _, tr := range zdr.Tracking[zone][agentId][rrtype].Tracked {
									if tr.RR.String() == rrStr {
										info.State = tr.State.String()
										info.Reason = tr.Reason
										info.DistributionID = tr.DistributionID
										info.UpdatedAt = tr.UpdatedAt.Format(time.RFC3339)
										info.Confirmations = tr.Confirmations
										break
									}
								}
							}
							infos = append(infos, info)
						}

						// Add tracking-only entries (e.g. Removed, PendingRemoval)
						// that are no longer in the active repo
						if zdr.Tracking[zone] != nil &&
							zdr.Tracking[zone][agentId] != nil &&
							zdr.Tracking[zone][agentId][rrtype] != nil {
							for _, tr := range zdr.Tracking[zone][agentId][rrtype].Tracked {
								trStr := tr.RR.String()
								if !activeRRs[trStr] {
									infos = append(infos, TrackedRRInfo{
										RR:             trStr,
										State:          tr.State.String(),
										Reason:         tr.Reason,
										DistributionID: tr.DistributionID,
										UpdatedAt:      tr.UpdatedAt.Format(time.RFC3339),
										Confirmations:  tr.Confirmations,
									})
								}
							}
						}
						rrsetData[rrtype] = infos
					}

					// Also include rrtypes that exist only in tracking (no active RRs remain)
					if zdr.Tracking[zone] != nil && zdr.Tracking[zone][agentId] != nil {
						for rrtype, trackedRRset := range zdr.Tracking[zone][agentId] {
							if _, exists := rrsetData[rrtype]; exists {
								continue // Already handled above
							}
							var infos []TrackedRRInfo
							for _, tr := range trackedRRset.Tracked {
								infos = append(infos, TrackedRRInfo{
									RR:             tr.RR.String(),
									State:          tr.State.String(),
									Reason:         tr.Reason,
									DistributionID: tr.DistributionID,
									UpdatedAt:      tr.UpdatedAt.Format(time.RFC3339),
									Confirmations:  tr.Confirmations,
								})
							}
							if len(infos) > 0 {
								rrsetData[rrtype] = infos
							}
						}
					}
					return rrsetData
				}

				if sdcmd.Zone != "" {
					if agentRepo, ok := zdr.Repo.Get(sdcmd.Zone); ok {
						agentData := make(map[AgentId]map[uint16][]TrackedRRInfo)
						for agentId, ownerData := range agentRepo.Data.Items() {
							agentData[agentId] = dumpZoneAgent(sdcmd.Zone, agentId, ownerData)
						}
						dumpData[sdcmd.Zone] = agentData
					}
				} else {
					for zone, agentRepo := range zdr.Repo.Items() {
						agentData := make(map[AgentId]map[uint16][]TrackedRRInfo)
						for agentId, ownerData := range agentRepo.Data.Items() {
							agentData[agentId] = dumpZoneAgent(zone, agentId, ownerData)
						}
						dumpData[zone] = agentData
					}
				}

				sdcmd.Response <- &SynchedDataCmdResponse{
					Zone:     "",
					ZDR:      dumpData,
					Msg:      "Zone data repo dumped",
					Error:    false,
					ErrorMsg: "",
				}

			case "resync":
				if sdcmd.Response == nil {
					log.Printf("SynchedDataEngine: resync command has no response channel, skipping")
					continue
				}
				if sdcmd.Zone == "" {
					sdcmd.Response <- &SynchedDataCmdResponse{Error: true, ErrorMsg: "zone is required for resync"}
					continue
				}
				tm := conf.Internal.TransportManager
				if tm == nil {
					sdcmd.Response <- &SynchedDataCmdResponse{Error: true, ErrorMsg: "TransportManager not available"}
					continue
				}
				myAgentId := AgentId(conf.Agent.Identity)
				agentRepo, ok := zdr.Repo.Get(sdcmd.Zone)
				if !ok {
					sdcmd.Response <- &SynchedDataCmdResponse{Msg: fmt.Sprintf("No local data for zone %s", sdcmd.Zone)}
					continue
				}
				nod, ok := agentRepo.Data.Get(myAgentId)
				if !ok {
					sdcmd.Response <- &SynchedDataCmdResponse{Msg: fmt.Sprintf("No local contributions for zone %s", sdcmd.Zone)}
					continue
				}

				// Build ZoneUpdate from all local RRsets
				zu := &ZoneUpdate{
					Zone:    sdcmd.Zone,
					AgentId: myAgentId,
					RRsets:  make(map[uint16]core.RRset),
				}
				var totalRRs int
				for _, rrtype := range nod.RRtypes.Keys() {
					rrset, exists := nod.RRtypes.Get(rrtype)
					if !exists || len(rrset.RRs) == 0 {
						continue
					}
					cloned := *rrset.Clone()
					for i := range cloned.RRs {
						cloned.RRs[i].Header().Class = dns.ClassINET
					}
					zu.RRsets[rrtype] = cloned
					totalRRs += len(cloned.RRs)
				}

				if totalRRs == 0 {
					sdcmd.Response <- &SynchedDataCmdResponse{Msg: fmt.Sprintf("No RRs to resync for zone %s", sdcmd.Zone)}
					continue
				}

				// Enqueue for combiner + all zone agents (like a normal local update)
				distID := GenerateQueueDistributionID()
				_, err := tm.EnqueueForCombiner(sdcmd.Zone, zu, distID)
				if err != nil {
					sdcmd.Response <- &SynchedDataCmdResponse{Error: true, ErrorMsg: fmt.Sprintf("Combiner enqueue error: %v", err)}
					continue
				}
				resyncRecipients := tm.GetDistributionRecipients(sdcmd.Zone, false)
				zdr.MarkRRsPending(sdcmd.Zone, myAgentId, zu, distID, resyncRecipients)

				if err := tm.EnqueueForZoneAgents(sdcmd.Zone, zu, distID); err != nil {
					log.Printf("SynchedDataEngine: resync: failed to enqueue for zone agents: %v", err)
				}

				log.Printf("SynchedDataEngine: resync: re-sent %d RRs for zone %s (distID: %s)", totalRRs, sdcmd.Zone, distID)
				sdcmd.Response <- &SynchedDataCmdResponse{
					Msg: fmt.Sprintf("Re-synced %d RRs for zone %s (distID: %s)", totalRRs, sdcmd.Zone, distID),
				}
			}

		case detail := <-msgQs.Confirmation:
			log.Printf("SynchedDataEngine: Received confirmation from %s for distribution %s zone %s status=%s applied=%d removed=%d rejected=%d truncated=%v",
				detail.Source, detail.DistributionID, detail.Zone, detail.Status,
				len(detail.AppliedRecords), len(detail.RemovedRecords), len(detail.RejectedItems), detail.Truncated)
			zdr.ProcessConfirmation(detail, msgQs)
		}
	}
}

func (zdr *ZoneDataRepo) SendUpdate(update *SynchedDataUpdate) error {
	// 1. Send the update to the combiner.
	log.Printf("SynchedDataEngine: Sending update to combiner (NYI)")
	return nil
}

// getOrCreateTracking returns (or creates) the TrackedRRset for the given zone/agent/rrtype.
func (zdr *ZoneDataRepo) getOrCreateTracking(zone ZoneName, agent AgentId, rrtype uint16) *TrackedRRset {
	if zdr.Tracking[zone] == nil {
		zdr.Tracking[zone] = make(map[AgentId]map[uint16]*TrackedRRset)
	}
	if zdr.Tracking[zone][agent] == nil {
		zdr.Tracking[zone][agent] = make(map[uint16]*TrackedRRset)
	}
	if zdr.Tracking[zone][agent][rrtype] == nil {
		zdr.Tracking[zone][agent][rrtype] = &TrackedRRset{}
	}
	return zdr.Tracking[zone][agent][rrtype]
}

// removeTracking removes all tracking for a zone/agent/rrtype (used on ClassANY deletion).
func (zdr *ZoneDataRepo) removeTracking(zone ZoneName, agent AgentId, rrtype uint16) {
	if zdr.Tracking[zone] != nil && zdr.Tracking[zone][agent] != nil {
		delete(zdr.Tracking[zone][agent], rrtype)
	}
}

// removeTrackedRR removes a specific tracked RR by its string representation (used on ClassNONE deletion).
func (zdr *ZoneDataRepo) removeTrackedRR(zone ZoneName, agent AgentId, rrtype uint16, rrStr string) {
	if zdr.Tracking[zone] == nil || zdr.Tracking[zone][agent] == nil {
		return
	}
	tracked := zdr.Tracking[zone][agent][rrtype]
	if tracked == nil {
		return
	}
	for i := range tracked.Tracked {
		if tracked.Tracked[i].RR.String() == rrStr {
			tracked.Tracked = append(tracked.Tracked[:i], tracked.Tracked[i+1:]...)
			return
		}
	}
}

// MarkRRsPending marks all RRs in a ZoneUpdate as pending with the given distribution ID.
// Called after successful enqueue for combiner delivery.
// recipients is the list of expected confirmation sources (combiner + agents) for this distID.
// The RR transitions to accepted only after ALL recipients have confirmed.
//
// For ClassINET RRs: marks as RRStatePending (addition awaiting confirmation).
// For ClassNONE RRs: finds the matching existing tracked RR and marks it as RRStatePendingRemoval.
// For ClassANY RRs: marks all tracked RRs for the rrtype as RRStatePendingRemoval.
func (zdr *ZoneDataRepo) MarkRRsPending(zone ZoneName, agent AgentId, update *ZoneUpdate, distID string, recipients []string) {
	now := time.Now()

	// Handle RRsets (remote updates)
	for rrtype, rrset := range update.RRsets {
		tracked := zdr.getOrCreateTracking(zone, agent, rrtype)
		for _, rr := range rrset.RRs {
			switch rr.Header().Class {
			case dns.ClassINET:
				zdr.markAddPending(tracked, rr, distID, now)
			case dns.ClassNONE:
				zdr.markDeletePending(tracked, rr, distID, now)
			case dns.ClassANY:
				zdr.markAllDeletePending(tracked, distID, now)
			}
		}
	}

	// Handle individual RRs (local updates)
	for _, rr := range update.RRs {
		rrtype := rr.Header().Rrtype
		tracked := zdr.getOrCreateTracking(zone, agent, rrtype)
		switch rr.Header().Class {
		case dns.ClassINET:
			zdr.markAddPending(tracked, rr, distID, now)
		case dns.ClassNONE:
			zdr.markDeletePending(tracked, rr, distID, now)
		case dns.ClassANY:
			zdr.markAllDeletePending(tracked, distID, now)
		}
	}

	// Set ExpectedRecipients on all TrackedRRs that now carry this distID.
	// This tells ProcessConfirmation who must confirm before state can transition.
	if len(recipients) > 0 {
		zdr.setExpectedRecipients(zone, agent, distID, recipients)
	}
}

// markAddPending marks a ClassINET RR as pending (addition awaiting confirmation).
func (zdr *ZoneDataRepo) markAddPending(tracked *TrackedRRset, rr dns.RR, distID string, now time.Time) {
	rrStr := rr.String()
	for i := range tracked.Tracked {
		if tracked.Tracked[i].RR.String() == rrStr {
			tracked.Tracked[i].State = RRStatePending
			tracked.Tracked[i].Reason = ""
			tracked.Tracked[i].DistributionID = distID
			tracked.Tracked[i].UpdatedAt = now
			return
		}
	}
	tracked.Tracked = append(tracked.Tracked, TrackedRR{
		RR:             rr,
		State:          RRStatePending,
		DistributionID: distID,
		UpdatedAt:      now,
	})
}

// markDeletePending finds the existing tracked RR matching the ClassNONE RR and
// transitions it to RRStatePendingRemoval. Matching is done by comparing the RR
// string with class normalized to ClassINET, since tracked RRs were stored with ClassINET.
func (zdr *ZoneDataRepo) markDeletePending(tracked *TrackedRRset, rr dns.RR, distID string, now time.Time) {
	// Create a ClassINET copy for matching against tracked RRs
	matchRR := dns.Copy(rr)
	matchRR.Header().Class = dns.ClassINET
	matchStr := matchRR.String()

	for i := range tracked.Tracked {
		if tracked.Tracked[i].RR.String() == matchStr {
			tracked.Tracked[i].State = RRStatePendingRemoval
			tracked.Tracked[i].Reason = ""
			tracked.Tracked[i].DistributionID = distID
			tracked.Tracked[i].UpdatedAt = now
			log.Printf("SynchedDataEngine: Marked RR as pending-removal: %s (dist=%s)", matchStr, distID)
			return
		}
	}
	log.Printf("SynchedDataEngine: markDeletePending: no matching tracked RR found for %s", matchStr)
}

// markAllDeletePending marks all tracked RRs in the RRset as RRStatePendingRemoval (ClassANY delete).
func (zdr *ZoneDataRepo) markAllDeletePending(tracked *TrackedRRset, distID string, now time.Time) {
	for i := range tracked.Tracked {
		if tracked.Tracked[i].State == RRStateAccepted || tracked.Tracked[i].State == RRStatePending {
			tracked.Tracked[i].State = RRStatePendingRemoval
			tracked.Tracked[i].Reason = ""
			tracked.Tracked[i].DistributionID = distID
			tracked.Tracked[i].UpdatedAt = now
		}
	}
}

// setExpectedRecipients sets the ExpectedRecipients on all TrackedRRs matching a given distID.
func (zdr *ZoneDataRepo) setExpectedRecipients(zone ZoneName, agent AgentId, distID string, recipients []string) {
	if zdr.Tracking[zone] == nil || zdr.Tracking[zone][agent] == nil {
		return
	}
	for _, trackedRRset := range zdr.Tracking[zone][agent] {
		for i := range trackedRRset.Tracked {
			if trackedRRset.Tracked[i].DistributionID == distID {
				trackedRRset.Tracked[i].ExpectedRecipients = recipients
			}
		}
	}
}

// allRecipientsConfirmed returns true if every expected recipient has sent a
// non-pending confirmation (accepted, removed, rejected). If ExpectedRecipients
// is empty (legacy/unset), returns true immediately for backwards compatibility.
func allRecipientsConfirmed(tr *TrackedRR) bool {
	if len(tr.ExpectedRecipients) == 0 {
		return true // No tracking — behave as before
	}
	for _, r := range tr.ExpectedRecipients {
		c, ok := tr.Confirmations[r]
		if !ok || c.Status == "pending" {
			return false
		}
	}
	return true
}

// ProcessConfirmation updates tracked RR states based on combiner confirmation feedback.
// For additions: Pending → Accepted or Rejected.
// For deletions: PendingRemoval → Removed (and the RR is actually deleted from the ZoneDataRepo).
// If a PendingRemoval RR appears in the rejected list, it transitions back to Accepted.
func (zdr *ZoneDataRepo) ProcessConfirmation(detail *ConfirmationDetail, msgQs *MsgQs) {
	now := time.Now()
	source := detail.Source
	if source == "" {
		source = "unknown"
	}

	// Helper to record per-recipient confirmation on a TrackedRR.
	setConfirmation := func(tr *TrackedRR, status, reason string) {
		if tr.Confirmations == nil {
			tr.Confirmations = make(map[string]RRConfirmation)
		}
		tr.Confirmations[source] = RRConfirmation{
			Status:    status,
			Reason:    reason,
			Timestamp: now,
		}
	}

	// First NOTIFY in two-phase protocol: status="PENDING" means the remote peer
	// received the sync and is processing it. Record per-recipient pending status.
	if detail.Status == "PENDING" {
		log.Printf("SynchedDataEngine: ProcessConfirmation(%s): pending confirmation for dist %s zone %s (delivery confirmed, awaiting final response)",
			source, detail.DistributionID, detail.Zone)
		zoneTracking := zdr.Tracking[detail.Zone]
		if zoneTracking != nil {
			for _, agentTracking := range zoneTracking {
				for _, trackedRRset := range agentTracking {
					for i := range trackedRRset.Tracked {
						tr := &trackedRRset.Tracked[i]
						if tr.DistributionID == detail.DistributionID {
							setConfirmation(tr, "pending", "")
						}
					}
				}
			}
		}
		return
	}

	// Build a set of applied RR strings for fast lookup
	appliedSet := make(map[string]bool, len(detail.AppliedRecords))
	for _, rr := range detail.AppliedRecords {
		appliedSet[rr] = true
	}

	// Build a set of removed RR strings for fast lookup
	removedSet := make(map[string]bool, len(detail.RemovedRecords))
	for _, rr := range detail.RemovedRecords {
		removedSet[rr] = true
	}

	// Build a map of rejected RR strings → reason
	rejectedMap := make(map[string]string, len(detail.RejectedItems))
	for _, ri := range detail.RejectedItems {
		rejectedMap[ri.Record] = ri.Reason
	}

	// Walk all tracked RRs for this zone and match by distribution ID + RR string
	zoneTracking := zdr.Tracking[detail.Zone]
	if zoneTracking == nil {
		log.Printf("SynchedDataEngine: ProcessConfirmation(%s): no tracking data for zone %s", source, detail.Zone)
		return
	}

	matched := 0
	removed := 0
	for agentId, agentTracking := range zoneTracking {
		for rrtype, trackedRRset := range agentTracking {
			for i := range trackedRRset.Tracked {
				tr := &trackedRRset.Tracked[i]
				if tr.DistributionID != detail.DistributionID {
					continue // Wrong distribution
				}
				rrStr := tr.RR.String()

				switch tr.State {
				case RRStatePending:
					// Addition confirmation
					if appliedSet[rrStr] {
						setConfirmation(tr, "accepted", "")
						tr.UpdatedAt = now
						matched++
						// Only transition to Accepted if ALL expected recipients have confirmed.
						if allRecipientsConfirmed(tr) {
							tr.State = RRStateAccepted
							tr.Reason = ""
						}
					} else if reason, rejected := rejectedMap[rrStr]; rejected {
						setConfirmation(tr, "rejected", reason)
						// Any rejection immediately transitions to Rejected
						tr.State = RRStateRejected
						tr.Reason = reason
						tr.UpdatedAt = now
						matched++
					}
					// If truncated and RR not in either list, leave as pending

				case RRStatePendingRemoval:
					if removedSet[rrStr] {
						setConfirmation(tr, "removed", "")
						tr.UpdatedAt = now
						matched++
						// Only transition to Removed and delete from repo if ALL expected recipients confirmed.
						if allRecipientsConfirmed(tr) {
							tr.State = RRStateRemoved
							tr.Reason = ""
							removed++
							zdr.deleteRRFromRepo(detail.Zone, agentId, rrtype, tr.RR)
							log.Printf("SynchedDataEngine: ProcessConfirmation(%s): RR removed (all confirmed): %s", source, rrStr)
						}
					} else if reason, rejected := rejectedMap[rrStr]; rejected {
						// Combiner rejected the delete — RR is still live, revert to Accepted
						setConfirmation(tr, "rejected", reason)
						tr.State = RRStateAccepted
						tr.Reason = fmt.Sprintf("delete rejected: %s", reason)
						tr.UpdatedAt = now
						matched++
						log.Printf("SynchedDataEngine: ProcessConfirmation(%s): delete rejected for RR: %s reason: %s", source, rrStr, reason)
					}
					// If truncated and RR not in either list, leave as pending-removal

				case RRStateAccepted:
					// Already accepted — record this recipient's confirmation
					if appliedSet[rrStr] {
						setConfirmation(tr, "accepted", "")
						matched++
					}

				case RRStateRemoved:
					// Already removed — record this recipient's confirmation
					if removedSet[rrStr] {
						setConfirmation(tr, "removed", "")
						matched++
					}
				}
			}
		}
	}

	log.Printf("SynchedDataEngine: ProcessConfirmation(%s): distribution %s zone %s: matched %d RRs (applied=%d removed=%d rejected=%d truncated=%v)",
		source, detail.DistributionID, detail.Zone, matched, len(detail.AppliedRecords), removed, len(detail.RejectedItems), detail.Truncated)

	// Check if this confirmation corresponds to a remote update we forwarded to our combiner.
	// If so, send the final confirmation back to the originating agent.
	if prc, ok := zdr.PendingRemoteConfirms[detail.DistributionID]; ok {
		log.Printf("SynchedDataEngine: ProcessConfirmation(%s): triggering remote confirmation for originating distID %s to %s",
			source, prc.OriginatingDistID, prc.OriginatingSender)
		remoteDetail := &RemoteConfirmationDetail{
			OriginatingDistID: prc.OriginatingDistID,
			OriginatingSender: prc.OriginatingSender,
			Zone:              prc.Zone,
			Status:            detail.Status,
			Message:           detail.Message,
			AppliedRecords:    detail.AppliedRecords,
			RemovedRecords:    detail.RemovedRecords,
			RejectedItems:     detail.RejectedItems,
			Truncated:         detail.Truncated,
		}
		if msgQs != nil && msgQs.OnRemoteConfirmationReady != nil {
			msgQs.OnRemoteConfirmationReady(remoteDetail)
		}
		delete(zdr.PendingRemoteConfirms, detail.DistributionID)
	}
}

// deleteRRFromRepo deletes a specific RR from the active ZoneDataRepo.
// Called when a PendingRemoval RR is confirmed as removed by the combiner.
func (zdr *ZoneDataRepo) deleteRRFromRepo(zone ZoneName, agent AgentId, rrtype uint16, rr dns.RR) {
	nar, ok := zdr.Repo.Get(zone)
	if !ok {
		return
	}
	nod, ok := nar.Get(agent)
	if !ok {
		return
	}
	curRRset, ok := nod.RRtypes.Get(rrtype)
	if !ok {
		return
	}
	curRRset.Delete(rr)
	nod.RRtypes.Set(rrtype, curRRset)
}
