/*
 * Copyright (c) 2024 Johan Stenstam, johani@johani.org
 */
package main

import (
	"context"
	"os"
	"os/signal"
	"syscall"

	tdns "github.com/johanix/tdns/v2"
	_ "github.com/johanix/tdns/v2/core" // Import for RR type registration
)

// Algorithm metadata is generated by genalgs (see algs.list): the
// generated metadata_algs.go registers metadata (name, codepoint, role)
// for every registry algorithm. tdns-cli doesn't sign or verify — it
// just needs to recognize the names/codepoints for CLI argument
// validation — so it selects NO real implementations (empty algs.list):
// no CIRCL, no liboqs, pure-Go build. Run tdns-genalgs --algrepo=<dir>
// before building; the generated file is a build artifact (gitignored).

func main() {
	tdns.Globals.App.Name = appName
	tdns.Globals.App.Version = appVersion
	tdns.Globals.App.Date = appDate

	// Create root context with signal handling
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	ExecuteContext(ctx)
}
