//go:build algdeps

// Code generated by genalgs; DO NOT EDIT.
//
// Committed, unlike the other genalgs output. registered_algs.go imports
// the same packages but is gitignored, so without this file go mod tidy
// in a fresh clone would drop their requirements from go.mod and go.sum.
// tidy reads a file whatever its build tags; no build sets "algdeps",
// so nothing here is compiled. genalgs rewrites this file from algs.list:
// commit it together with the list.

package main

import (
	_ "github.com/johanix/dnssec-algorithms/falcon512"   // FALCON512
	_ "github.com/johanix/dnssec-algorithms/mayo1"       // MAYO1
	_ "github.com/johanix/dnssec-algorithms/slhdsa128s"  // SLHDSA128S
	_ "github.com/johanix/dnssec-algorithms/snova24_5_4" // SNOVA24_5_4
)
