/*
 * Copyright (c) 2024 Johan Stenstam, johani@johani.org
 */
package cli

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	tdns "github.com/johanix/tdns/v2"
	"github.com/miekg/dns"
	"github.com/spf13/cobra"
)

// The "imr" subtree is replicated under each parent command that
// names a daemon hosting an in-process IMR (agent, auth, ...). The
// parent identifies which API client to use; the leaf commands are
// generated by the factory functions below so the logic lives in one
// place.

var agentImrCmd = &cobra.Command{
	Use:   "imr",
	Short: "IMR (Internal Recursive Resolver) cache commands",
}

var authImrCmd = &cobra.Command{
	Use:   "imr",
	Short: "IMR (Internal Recursive Resolver) cache commands",
}

func newImrQueryCmd(role string) *cobra.Command {
	return &cobra.Command{
		Use:   "query <qname> <qtype>",
		Short: "Query the IMR cache (cache-only, no external queries)",
		Args:  cobra.ExactArgs(2),
		Run: func(cmd *cobra.Command, args []string) {
			qname := dns.Fqdn(args[0])
			qtype := args[1]

			amr, err := SendImrMgmtCmd(role, &tdns.ImrMgmtPost{
				Command: "imr-query",
				Data: map[string]interface{}{
					"qname": qname,
					"qtype": qtype,
				},
			})
			if err != nil {
				log.Fatalf("Request failed: %v", err)
			}
			if amr.Error {
				fmt.Fprintf(os.Stderr, "Error: %s\n", amr.ErrorMsg)
				os.Exit(1)
			}

			fmt.Println(amr.Msg)
			if amr.Data != nil {
				data, ok := amr.Data.(map[string]interface{})
				if ok {
					if records, ok := data["records"].([]interface{}); ok {
						for _, rr := range records {
							fmt.Printf("  %s\n", rr)
						}
					}
					fmt.Printf("  TTL: %v  Expires in: %s  Rcode: %s  State: %s  Context: %s\n",
						data["ttl"], data["expires_in"], data["rcode"], data["state"], data["context"])
				} else {
					buf, err := json.MarshalIndent(amr.Data, "", "  ")
					if err != nil {
						fmt.Fprintf(os.Stderr, "failed to marshal response Data: %v\n", err)
					} else {
						fmt.Println(string(buf))
					}
				}
			}
		},
	}
}

func newImrFlushCmd(role string) *cobra.Command {
	return &cobra.Command{
		Use:   "flush <qname>",
		Short: "Flush IMR cache entries at and below qname",
		Args:  cobra.ExactArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			qname := dns.Fqdn(args[0])
			amr, err := SendImrMgmtCmd(role, &tdns.ImrMgmtPost{
				Command: "imr-flush",
				Data:    map[string]interface{}{"qname": qname},
			})
			if err != nil {
				log.Fatalf("Request failed: %v", err)
			}
			if amr.Error {
				fmt.Fprintf(os.Stderr, "Error: %s\n", amr.ErrorMsg)
				os.Exit(1)
			}
			fmt.Println(amr.Msg)
		},
	}
}

func newImrResetCmd(role string) *cobra.Command {
	return &cobra.Command{
		Use:   "reset",
		Short: "Flush entire IMR cache and re-prime (preserves root NS)",
		Run: func(cmd *cobra.Command, args []string) {
			amr, err := SendImrMgmtCmd(role, &tdns.ImrMgmtPost{Command: "imr-reset"})
			if err != nil {
				log.Fatalf("Request failed: %v", err)
			}
			if amr.Error {
				fmt.Fprintf(os.Stderr, "Error: %s\n", amr.ErrorMsg)
				os.Exit(1)
			}
			fmt.Println(amr.Msg)
		},
	}
}

func newImrShowCmd(role string) *cobra.Command {
	var imrShowID string
	cmd := &cobra.Command{
		Use:   "show",
		Short: "Show IMR cache entries related to agent discovery",
		Run: func(cmd *cobra.Command, args []string) {
			if imrShowID == "" {
				log.Fatal("--id flag is required")
			}
			amr, err := SendImrMgmtCmd(role, &tdns.ImrMgmtPost{
				Command: "imr-show",
				Id:      imrShowID,
			})
			if err != nil {
				log.Fatalf("Request failed: %v", err)
			}
			if amr.Error {
				fmt.Fprintf(os.Stderr, "Error: %s\n", amr.ErrorMsg)
				os.Exit(1)
			}
			fmt.Println(amr.Msg)
			if amr.Data != nil {
				entries, ok := amr.Data.([]interface{})
				if ok {
					for _, e := range entries {
						entry, ok := e.(map[string]interface{})
						if !ok {
							continue
						}
						fmt.Printf("  %s %s", entry["name"], entry["rrtype"])
						if records, ok := entry["records"].([]interface{}); ok && len(records) > 0 {
							fmt.Println(":")
							for _, rr := range records {
								fmt.Printf("    %s\n", rr)
							}
						} else {
							fmt.Printf("  (rcode: %s)\n", entry["rcode"])
						}
						fmt.Printf("    TTL: %v  Expires in: %s\n", entry["ttl"], entry["expires_in"])
					}
				} else {
					buf, err := json.MarshalIndent(amr.Data, "", "  ")
					if err != nil {
						fmt.Fprintf(os.Stderr, "failed to marshal response Data: %v\n", err)
					} else {
						fmt.Println(string(buf))
					}
				}
			}
		},
	}
	cmd.Flags().StringVar(&imrShowID, "id", "", "Agent identity to show cache entries for (required)")
	return cmd
}

func newImrDumpTuningCmd(role string) *cobra.Command {
	return &cobra.Command{
		Use:   "dump-tuning",
		Short: "Show effective IMR tuning values (backoff policy, family, discovery, etc.)",
		Run: func(cmd *cobra.Command, args []string) {
			amr, err := SendImrMgmtCmd(role, &tdns.ImrMgmtPost{Command: "imr-dump-tuning"})
			if err != nil {
				log.Fatalf("Request failed: %v", err)
			}
			if amr.Error {
				fmt.Fprintf(os.Stderr, "Error: %s\n", amr.ErrorMsg)
				os.Exit(1)
			}
			data, ok := amr.Data.(map[string]interface{})
			if !ok {
				buf, err := json.MarshalIndent(amr.Data, "", "  ")
				if err != nil {
					fmt.Fprintf(os.Stderr, "failed to marshal response Data: %v\n", err)
				} else {
					fmt.Println(string(buf))
				}
				return
			}
			printSection := func(title string, key string) {
				sect, _ := data[key].(map[string]interface{})
				if sect == nil {
					return
				}
				fmt.Println(title)
				keys := make([]string, 0, len(sect))
				for k := range sect {
					keys = append(keys, k)
				}
				sort.Strings(keys)
				for _, k := range keys {
					fmt.Printf("  %-20s: %v\n", k, sect[k])
				}
			}
			printSection("Backoff policy (effective):", "backoff")
			printSection("Address-family tracker (config; activates with W8):", "address_family")
			printSection("Discovery state machine (config; activates with W9):", "discovery")
			fmt.Printf("Per-query budget          : %v\n", data["query_budget"])
			fmt.Printf("Upgrade indirect cache hits: %v\n", data["upgrade_indirect_cache_hits"])
		},
	}
}

func newImrDumpZoneBackoffsCmd(role string) *cobra.Command {
	return &cobra.Command{
		Use:   "dump-zone-backoffs [zone]",
		Short: "Show zone-scoped lame-delegation backoffs (per zone, per address)",
		Args:  cobra.MaximumNArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			data := map[string]interface{}{}
			if len(args) == 1 {
				data["zone"] = dns.Fqdn(args[0])
			}
			amr, err := SendImrMgmtCmd(role, &tdns.ImrMgmtPost{
				Command: "imr-dump-zone-backoffs",
				Data:    data,
			})
			if err != nil {
				log.Fatalf("Request failed: %v", err)
			}
			if amr.Error {
				fmt.Fprintf(os.Stderr, "Error: %s\n", amr.ErrorMsg)
				os.Exit(1)
			}
			fmt.Println(amr.Msg)
			records, ok := amr.Data.([]interface{})
			if !ok || len(records) == 0 {
				return
			}
			fmt.Println("Zone | Address | Remaining | Failures | Error")
			fmt.Println(strings.Repeat("-", 80))
			for _, r := range records {
				rec, ok := r.(map[string]interface{})
				if !ok {
					continue
				}
				errMsg := "-"
				if e, _ := rec["last_error"].(string); e != "" {
					errMsg = e
				}
				fmt.Printf("%s | %s | %s | %v | %s\n",
					rec["zone"], rec["address"], rec["remaining"], rec["failure_count"], errMsg)
			}
		},
	}
}

func addImrLeafCmds(parent *cobra.Command, role string) {
	parent.AddCommand(
		newImrQueryCmd(role),
		newImrFlushCmd(role),
		newImrResetCmd(role),
		newImrShowCmd(role),
		newImrDumpTuningCmd(role),
		newImrDumpZoneBackoffsCmd(role),
	)
}

func init() {
	AgentCmd.AddCommand(agentImrCmd)
	addImrLeafCmds(agentImrCmd, "agent")

	AuthCmd.AddCommand(authImrCmd)
	addImrLeafCmds(authImrCmd, "auth")
}
