/*
 * Copyright (c) 2024 Johan Stenstam, johani@johani.org
 */
package cli

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	tdns "github.com/johanix/tdns/v2"
	"github.com/miekg/dns"
	"github.com/spf13/cobra"
)

// The "imr" subtree is replicated under each parent command that
// names a daemon hosting an in-process IMR (agent, auth, ...). The
// parent identifies which API client to use; the leaf commands are
// generated by the factory functions below so the logic lives in one
// place.

var agentImrCmd = &cobra.Command{
	Use:   "imr",
	Short: "IMR (Internal Recursive Resolver) cache commands",
}

var authImrCmd = &cobra.Command{
	Use:   "imr",
	Short: "IMR (Internal Recursive Resolver) cache commands",
}

func newImrQueryCmd(role string) *cobra.Command {
	return &cobra.Command{
		Use:   "query <qname> <qtype>",
		Short: "Query the IMR cache (cache-only, no external queries)",
		Args:  cobra.ExactArgs(2),
		Run: func(cmd *cobra.Command, args []string) {
			qname := dns.Fqdn(args[0])
			qtype := args[1]

			amr, err := SendImrMgmtCmd(role, &tdns.ImrMgmtPost{
				Command: "imr-query",
				Data: map[string]interface{}{
					"qname": qname,
					"qtype": qtype,
				},
			})
			if err != nil {
				log.Fatalf("Request failed: %v", err)
			}
			if amr.Error {
				fmt.Fprintf(os.Stderr, "Error: %s\n", amr.ErrorMsg)
				os.Exit(1)
			}

			fmt.Println(amr.Msg)
			if amr.Data != nil {
				data, ok := amr.Data.(map[string]interface{})
				if ok {
					if records, ok := data["records"].([]interface{}); ok {
						for _, rr := range records {
							fmt.Printf("  %s\n", rr)
						}
					}
					fmt.Printf("  TTL: %v  Expires in: %s  Rcode: %s  State: %s  Context: %s\n",
						data["ttl"], data["expires_in"], data["rcode"], data["state"], data["context"])
				} else {
					buf, err := json.MarshalIndent(amr.Data, "", "  ")
					if err != nil {
						fmt.Fprintf(os.Stderr, "failed to marshal response Data: %v\n", err)
					} else {
						fmt.Println(string(buf))
					}
				}
			}
		},
	}
}

func newImrFlushCmd(role string) *cobra.Command {
	return &cobra.Command{
		Use:   "flush <qname>",
		Short: "Flush IMR cache entries at and below qname",
		Args:  cobra.ExactArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			qname := dns.Fqdn(args[0])
			amr, err := SendImrMgmtCmd(role, &tdns.ImrMgmtPost{
				Command: "imr-flush",
				Data:    map[string]interface{}{"qname": qname},
			})
			if err != nil {
				log.Fatalf("Request failed: %v", err)
			}
			if amr.Error {
				fmt.Fprintf(os.Stderr, "Error: %s\n", amr.ErrorMsg)
				os.Exit(1)
			}
			fmt.Println(amr.Msg)
		},
	}
}

func newImrResetCmd(role string) *cobra.Command {
	return &cobra.Command{
		Use:   "reset",
		Short: "Flush entire IMR cache and re-prime (preserves root NS)",
		Run: func(cmd *cobra.Command, args []string) {
			amr, err := SendImrMgmtCmd(role, &tdns.ImrMgmtPost{Command: "imr-reset"})
			if err != nil {
				log.Fatalf("Request failed: %v", err)
			}
			if amr.Error {
				fmt.Fprintf(os.Stderr, "Error: %s\n", amr.ErrorMsg)
				os.Exit(1)
			}
			fmt.Println(amr.Msg)
		},
	}
}

func newImrShowCmd(role string) *cobra.Command {
	var imrShowID string
	cmd := &cobra.Command{
		Use:   "show",
		Short: "Show IMR cache entries related to agent discovery",
		Run: func(cmd *cobra.Command, args []string) {
			if imrShowID == "" {
				log.Fatal("--id flag is required")
			}
			amr, err := SendImrMgmtCmd(role, &tdns.ImrMgmtPost{
				Command: "imr-show",
				Id:      imrShowID,
			})
			if err != nil {
				log.Fatalf("Request failed: %v", err)
			}
			if amr.Error {
				fmt.Fprintf(os.Stderr, "Error: %s\n", amr.ErrorMsg)
				os.Exit(1)
			}
			fmt.Println(amr.Msg)
			if amr.Data != nil {
				entries, ok := amr.Data.([]interface{})
				if ok {
					for _, e := range entries {
						entry, ok := e.(map[string]interface{})
						if !ok {
							continue
						}
						fmt.Printf("  %s %s", entry["name"], entry["rrtype"])
						if records, ok := entry["records"].([]interface{}); ok && len(records) > 0 {
							fmt.Println(":")
							for _, rr := range records {
								fmt.Printf("    %s\n", rr)
							}
						} else {
							fmt.Printf("  (rcode: %s)\n", entry["rcode"])
						}
						fmt.Printf("    TTL: %v  Expires in: %s\n", entry["ttl"], entry["expires_in"])
					}
				} else {
					buf, err := json.MarshalIndent(amr.Data, "", "  ")
					if err != nil {
						fmt.Fprintf(os.Stderr, "failed to marshal response Data: %v\n", err)
					} else {
						fmt.Println(string(buf))
					}
				}
			}
		},
	}
	cmd.Flags().StringVar(&imrShowID, "id", "", "Agent identity to show cache entries for (required)")
	return cmd
}

func newImrDumpTuningCmd(role string) *cobra.Command {
	return &cobra.Command{
		Use:   "dump-tuning",
		Short: "Show effective IMR tuning values (backoff policy, family, discovery, etc.)",
		Run: func(cmd *cobra.Command, args []string) {
			amr, err := SendImrMgmtCmd(role, &tdns.ImrMgmtPost{Command: "imr-dump-tuning"})
			if err != nil {
				log.Fatalf("Request failed: %v", err)
			}
			if amr.Error {
				fmt.Fprintf(os.Stderr, "Error: %s\n", amr.ErrorMsg)
				os.Exit(1)
			}
			data, ok := amr.Data.(map[string]interface{})
			if !ok {
				buf, err := json.MarshalIndent(amr.Data, "", "  ")
				if err != nil {
					fmt.Fprintf(os.Stderr, "failed to marshal response Data: %v\n", err)
				} else {
					fmt.Println(string(buf))
				}
				return
			}
			printSection := func(title string, key string) {
				sect, _ := data[key].(map[string]interface{})
				if sect == nil {
					return
				}
				fmt.Println(title)
				keys := make([]string, 0, len(sect))
				for k := range sect {
					keys = append(keys, k)
				}
				sort.Strings(keys)
				for _, k := range keys {
					fmt.Printf("  %-20s: %v\n", k, sect[k])
				}
			}
			printSection("Backoff policy (effective):", "backoff")
			printSection("Address-family tracker (config; activates with W8):", "address_family")
			printSection("Discovery state machine (config; activates with W9):", "discovery")
			fmt.Printf("Per-query budget          : %v\n", data["query_budget"])
			fmt.Printf("Upgrade indirect cache hits: %v\n", data["upgrade_indirect_cache_hits"])
		},
	}
}

func newImrDumpZoneBackoffsCmd(role string) *cobra.Command {
	return &cobra.Command{
		Use:   "dump-zone-backoffs [zone]",
		Short: "Show zone-scoped lame-delegation backoffs (per zone, per address)",
		Args:  cobra.MaximumNArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			data := map[string]interface{}{}
			if len(args) == 1 {
				data["zone"] = dns.Fqdn(args[0])
			}
			amr, err := SendImrMgmtCmd(role, &tdns.ImrMgmtPost{
				Command: "imr-dump-zone-backoffs",
				Data:    data,
			})
			if err != nil {
				log.Fatalf("Request failed: %v", err)
			}
			if amr.Error {
				fmt.Fprintf(os.Stderr, "Error: %s\n", amr.ErrorMsg)
				os.Exit(1)
			}
			fmt.Println(amr.Msg)
			records, ok := amr.Data.([]interface{})
			if !ok || len(records) == 0 {
				return
			}
			fmt.Println("Zone | Address | Remaining | Failures | Error")
			fmt.Println(strings.Repeat("-", 80))
			for _, r := range records {
				rec, ok := r.(map[string]interface{})
				if !ok {
					continue
				}
				errMsg := "-"
				if e, _ := rec["last_error"].(string); e != "" {
					errMsg = e
				}
				fmt.Printf("%s | %s | %s | %v | %s\n",
					rec["zone"], rec["address"], rec["remaining"], rec["failure_count"], errMsg)
			}
		},
	}
}

// decodeImrData re-marshals the generic Data payload of an ImrMgmtResponse
// into its typed form. The /imr response carries Data as interface{}, so the
// JSON round-trip is the price of one shared response struct.
func decodeImrData[T any](amr *tdns.ImrMgmtResponse, out *T) error {
	b, err := json.Marshal(amr.Data)
	if err != nil {
		return err
	}
	return json.Unmarshal(b, out)
}

func imrMgmtOrDie(role string, post *tdns.ImrMgmtPost) *tdns.ImrMgmtResponse {
	amr, err := SendImrMgmtCmd(role, post)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}
	if amr.Error {
		fmt.Printf("Error: %s\n", amr.ErrorMsg)
		os.Exit(1)
	}
	return amr
}

// --- forward zones: list / status / probe ----------------------------------

func newImrForwardCmd(role string) *cobra.Command {
	c := &cobra.Command{
		Use:   "forward",
		Short: "Inspect and probe the IMR's forward zones",
	}
	c.AddCommand(
		&cobra.Command{
			Use:   "list",
			Short: "List the configured forward zones and their upstreams",
			Args:  cobra.NoArgs,
			Run: func(cmd *cobra.Command, args []string) {
				amr := imrMgmtOrDie(role, &tdns.ImrMgmtPost{Command: "imr-forward-list"})
				var zones []tdns.ImrForwardZoneInfo
				if err := decodeImrData(amr, &zones); err != nil {
					fmt.Printf("Error decoding response: %v\n", err)
					os.Exit(1)
				}
				if len(zones) == 0 {
					fmt.Println("No forward zones configured")
					return
				}
				for _, fz := range zones {
					trust := ""
					if fz.TrustAD {
						trust = "  (trust-ad)"
					}
					fmt.Printf("%s%s\n", fz.Zone, trust)
					for _, up := range fz.Upstreams {
						line := "  " + up.Upstream
						if up.TLSServerName != "" {
							line += "  tls-server-name=" + up.TLSServerName
						}
						if up.Insecure {
							line += "  INSECURE (no certificate verification)"
						}
						fmt.Println(line)
					}
				}
			},
		},
		&cobra.Command{
			Use:   "status",
			Short: "Show per-upstream reachability, counters and last success/error",
			Args:  cobra.NoArgs,
			Run: func(cmd *cobra.Command, args []string) {
				amr := imrMgmtOrDie(role, &tdns.ImrMgmtPost{Command: "imr-forward-status"})
				var zones []tdns.ImrForwardZoneStatus
				if err := decodeImrData(amr, &zones); err != nil {
					fmt.Printf("Error decoding response: %v\n", err)
					os.Exit(1)
				}
				if len(zones) == 0 {
					fmt.Println("No forward zones configured")
					return
				}
				for _, fz := range zones {
					printForwardZoneStatus(fz, "")
				}
			},
		},
		&cobra.Command{
			Use:   "probe [zone]",
			Short: "Probe the forward upstreams now (same probe as at startup) and report per upstream",
			Long: `Send a recursive '. NS' probe to every upstream of the configured forward
zones (or of one zone) and report the outcome per upstream. The probe updates
the live reachability state, so a recovered upstream clears its DEGRADED
error and a newly dead one raises it.`,
			Args: cobra.MaximumNArgs(1),
			Run: func(cmd *cobra.Command, args []string) {
				post := &tdns.ImrMgmtPost{Command: "imr-forward-probe"}
				if len(args) == 1 {
					post.Zone = tdns.ZoneName(dns.Fqdn(args[0]))
				}
				amr := imrMgmtOrDie(role, post)
				var results []tdns.ImrForwardProbeResult
				if err := decodeImrData(amr, &results); err != nil {
					fmt.Printf("Error decoding response: %v\n", err)
					os.Exit(1)
				}
				if len(results) == 0 {
					fmt.Println("No forward upstreams to probe")
					return
				}
				failed := 0
				for _, res := range results {
					if res.OK {
						fmt.Printf("ok      %-20s %-30s rtt %s\n", res.Zone, res.Upstream, res.RTT)
					} else {
						failed++
						fmt.Printf("FAILED  %-20s %-30s rtt %s: %s\n", res.Zone, res.Upstream, res.RTT, res.Error)
					}
				}
				if failed > 0 {
					fmt.Printf("\n%d of %d upstream(s) unreachable\n", failed, len(results))
					os.Exit(1)
				}
			},
		},
	)
	return c
}

// --- stub zones: list / status / probe -------------------------------------

func newImrStubCmd(role string) *cobra.Command {
	c := &cobra.Command{
		Use:   "stub",
		Short: "Inspect and probe the IMR's stub zones",
	}
	c.AddCommand(
		&cobra.Command{
			Use:   "list",
			Short: "List the configured stub zones and their servers",
			Args:  cobra.NoArgs,
			Run: func(cmd *cobra.Command, args []string) {
				amr := imrMgmtOrDie(role, &tdns.ImrMgmtPost{Command: "imr-stub-list"})
				var zones []tdns.ImrStubZoneInfo
				if err := decodeImrData(amr, &zones); err != nil {
					fmt.Printf("Error decoding response: %v\n", err)
					os.Exit(1)
				}
				if len(zones) == 0 {
					fmt.Println("No stub zones configured")
					return
				}
				for _, sz := range zones {
					fmt.Println(sz.Zone)
					for _, server := range sz.Servers {
						fmt.Printf("  %s  addrs=%s  alpn=%s\n", server.Name,
							strings.Join(server.Addrs, ","), strings.Join(server.Alpn, ","))
					}
				}
			},
		},
		&cobra.Command{
			Use:   "status",
			Short: "Show per-server transport counters and active backoffs",
			Args:  cobra.NoArgs,
			Run: func(cmd *cobra.Command, args []string) {
				amr := imrMgmtOrDie(role, &tdns.ImrMgmtPost{Command: "imr-stub-status"})
				var zones []tdns.ImrStubZoneStatus
				if err := decodeImrData(amr, &zones); err != nil {
					fmt.Printf("Error decoding response: %v\n", err)
					os.Exit(1)
				}
				if len(zones) == 0 {
					fmt.Println("No stub zones configured")
					return
				}
				formatCounters := func(m map[string]uint64) string {
					if len(m) == 0 {
						return "none"
					}
					keys := make([]string, 0, len(m))
					for k := range m {
						keys = append(keys, k)
					}
					sort.Strings(keys)
					parts := make([]string, 0, len(keys))
					for _, k := range keys {
						parts = append(parts, fmt.Sprintf("%s:%d", k, m[k]))
					}
					return strings.Join(parts, " ")
				}
				for _, sz := range zones {
					fmt.Printf("stub zone %s (%d server(s)):\n", sz.Zone, len(sz.Servers))
					for _, server := range sz.Servers {
						fmt.Printf("  %s  addrs=%s  transports=%s\n", server.Name,
							strings.Join(server.Addrs, ","), strings.Join(server.Transports, ","))
						fmt.Printf("    attempted=%s used=%s failed=%s truncated=%d\n",
							formatCounters(server.Attempted), formatCounters(server.Used),
							formatCounters(server.Failed), server.Truncated)
						if len(server.Backoffs) == 0 {
							fmt.Printf("    backoffs: none\n")
						} else {
							fmt.Printf("    backoffs (queries to these are currently SUPPRESSED):\n")
							for _, b := range server.Backoffs {
								fmt.Printf("      %s\n", b)
							}
						}
					}
				}
			},
		},
		&cobra.Command{
			Use:   "probe [zone]",
			Short: "Probe the stub servers now and report per (server, address, transport)",
			Long: `Send an RD=0 SOA query for the stub zone to every (server, address,
advertised transport) tuple and report rcode, AA bit and RTT. Strictly
report-only: nothing is recorded into the resolver's server state, so a
probe can never put a stub server into backoff.`,
			Args: cobra.MaximumNArgs(1),
			Run: func(cmd *cobra.Command, args []string) {
				post := &tdns.ImrMgmtPost{Command: "imr-stub-probe"}
				if len(args) == 1 {
					post.Zone = tdns.ZoneName(dns.Fqdn(args[0]))
				}
				amr := imrMgmtOrDie(role, post)
				var results []tdns.ImrStubProbeResult
				if err := decodeImrData(amr, &results); err != nil {
					fmt.Printf("Error decoding response: %v\n", err)
					os.Exit(1)
				}
				if len(results) == 0 {
					fmt.Println("No stub servers to probe")
					return
				}
				failed := 0
				for _, res := range results {
					where := fmt.Sprintf("%s @ %s/%s", res.Server, res.Addr, res.Transport)
					switch {
					case res.Error != "":
						failed++
						fmt.Printf("FAILED  %-20s %-45s rtt %s: %s\n", res.Zone, where, res.RTT, res.Error)
					case !res.OK:
						failed++
						fmt.Printf("BAD     %-20s %-45s rtt %s: rcode=%s aa=%v\n", res.Zone, where, res.RTT, res.Rcode, res.AA)
					default:
						fmt.Printf("ok      %-20s %-45s rtt %s\n", res.Zone, where, res.RTT)
					}
				}
				if failed > 0 {
					fmt.Printf("\n%d of %d server tuple(s) not answering authoritatively\n", failed, len(results))
					os.Exit(1)
				}
			},
		},
	)
	return c
}

func addImrLeafCmds(parent *cobra.Command, role string) {
	parent.AddCommand(
		newImrQueryCmd(role),
		newImrFlushCmd(role),
		newImrResetCmd(role),
		newImrShowCmd(role),
		newImrDumpTuningCmd(role),
		newImrDumpZoneBackoffsCmd(role),
		newImrForwardCmd(role),
		newImrStubCmd(role),
	)
}

func init() {
	AgentCmd.AddCommand(agentImrCmd)
	addImrLeafCmds(agentImrCmd, "agent")

	AuthCmd.AddCommand(authImrCmd)
	addImrLeafCmds(authImrCmd, "auth")

	// The standalone tdns-imr daemon serves the same /imr endpoint, so the
	// forward/stub trees work against it directly (unlike the in-process
	// cache commands under `tdns-cli imr`, which need an embedded resolver).
	ImrCmd.AddCommand(newImrForwardCmd("imr"))
	ImrCmd.AddCommand(newImrStubCmd("imr"))
}
