//go:build algdeps

// Code generated by genalgs; DO NOT EDIT.
//
// Committed, unlike the other genalgs output. registered_algs.go imports
// the same packages but is gitignored, so without this file go mod tidy
// in a fresh clone would drop their requirements from go.mod and go.sum.
// tidy reads a file whatever its build tags; no build sets "algdeps",
// so nothing here is compiled. genalgs rewrites this file from algs.list:
// commit it together with the list.

package main

import (
	_ "github.com/johanix/dnssec-algorithms/cross_rsdpg_128_small" // CROSSRSDPG128SMALL
	_ "github.com/johanix/dnssec-algorithms/falcon1024"            // FALCON1024
	_ "github.com/johanix/dnssec-algorithms/falcon512"             // FALCON512
	_ "github.com/johanix/dnssec-algorithms/mayo1"                 // MAYO1
	_ "github.com/johanix/dnssec-algorithms/mayo2"                 // MAYO2
	_ "github.com/johanix/dnssec-algorithms/mayo3"                 // MAYO3
	_ "github.com/johanix/dnssec-algorithms/mayo5"                 // MAYO5
	_ "github.com/johanix/dnssec-algorithms/mldsa65"               // MLDSA65
	_ "github.com/johanix/dnssec-algorithms/mldsa87"               // MLDSA87
	_ "github.com/johanix/dnssec-algorithms/qruov_q31_l3"          // QRUOV_Q31_L3
	_ "github.com/johanix/dnssec-algorithms/slhdsa128s"            // SLHDSA128S
	_ "github.com/johanix/dnssec-algorithms/snova24_5_4"           // SNOVA24_5_4
	_ "github.com/johanix/dnssec-algorithms/snova25_8_3"           // SNOVA25_8_3
	_ "github.com/johanix/dnssec-algorithms/snova37_17_2"          // SNOVA37_17_2
	_ "github.com/johanix/dnssec-algorithms/sqisign1"              // SQISIGN1
)
