/*
 * Copyright (c) 2024 Johan Stenstam, johan.stenstam@internetstiftelsen.se
 */

package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"

	_ "github.com/mattn/go-sqlite3"

	tdns "github.com/johanix/tdns/v2"
)

// tdns-signer is tdns-auth under a different name, so that a signer and an
// authoritative server can run on the same host without their configuration
// colliding.
//
// The intended shape is a bump-on-the-wire signer in a transfer pipeline:
//
//	tdns-auth (unsigned, accepts file/UPDATE/API input)
//	    |  AXFR
//	    v
//	tdns-signer (secondary + inline-signing)
//	    |  AXFR
//	    v
//	published secondaries
//
// which is a zone declared `type: secondary` with the `inline-signing` option:
// a sanctioned, long-standing mode (see docs/2026-07-25-secondary-zones-
// immutable.md), not something this app adds. tdns-auth already refreshes from
// its primary, signs synchronously before publishing, and NOTIFYs its
// downstreams; the signer needs no new engine.
//
// WHY THIS IS A SEPARATE BINARY AT ALL: Globals.App.Name is what
// GetDefaultConfigFile derives the config path from, and it is a compile-time
// constant. So `tdns-auth` reads /etc/tdns/tdns-auth.yaml and this reads
// /etc/tdns/tdns-signer.yaml, with no --config on either. Two instances of one
// binary would need --config on one of them forever, and -- because these
// daemons write no pidfile, so NetBSD rc.subr matches $procname against the
// running command -- would also be indistinguishable to their own rc scripts,
// where either script's `stop` matches both. A distinct binary name settles
// both.
//
// Algorithm registration is generated by genalgs (see algs.list): the
// generated metadata_algs.go registers metadata for every registry
// algorithm, and registered_algs.go registers a real implementation for
// each algorithm this app selected. Run tdns-genalgs --algrepo=<dir>
// before building; the generated files are build artifacts (gitignored).

func main() {
	// AppTypeAuth, deliberately, not an AppTypeSigner of its own.
	//
	// A signer IS an authoritative server: it serves the zone, answers
	// queries, transfers out, runs the keystore and the rollover engine.
	// Every one of the ~15 places in v2/ that branch on AppTypeAuth wants the
	// same answer here as it gives tdns-auth -- and several of them are not
	// merely cosmetic. Two would break outright: the KeyDB is initialised only
	// for AppTypeAuth/Agent/Scanner (v2/main_initfuncs.go, v2/parseconfig.go),
	// so a new app type would come up with no keystore and be unable to sign
	// at all. Two others are safety gates that stand DOWN for any app type
	// that is not tdns-auth -- zoneMayOriginateContent (v2/zone_origination.go)
	// and HasExpired (v2/zone_refresh_state.go) -- so a new type would silently
	// lose them rather than fail loudly.
	//
	// The cost is that logs and the startup banner say mode "auth". The
	// benefit is that this app cannot drift from tdns-auth's behaviour by
	// having missed a branch. If the two ever need to diverge -- a signer that
	// declines to run DelegationSyncher, ScannerEngine or UpdateHandler, say --
	// that divergence is the reason to introduce AppTypeSigner, and the branch
	// sites become the design rather than overhead.
	tdns.Globals.App.Type = tdns.AppTypeAuth
	tdns.Globals.App.Version = appVersion
	tdns.Globals.App.Name = appName
	tdns.Globals.App.Date = appDate

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	conf := &tdns.Conf
	err := conf.MainInit(ctx, "") // Empty string means derive from Globals.App.Name
	if err != nil {
		tdns.Shutdowner(conf, fmt.Sprintf("Error initializing TDNS: %v", err))
	}

	// Write the rollover-daemon sentinel so CLI --offline writers
	// can detect we're alive and refuse to race the rollover tick.
	// Best-effort cleanup on graceful shutdown via defer; SIGKILL or
	// crash leaves the row stale, which the CLI's kill -0 check
	// handles correctly.
	if conf.Internal.KeyDB != nil {
		// Sentinel write must succeed: it's the gate that lets CLI
		// --offline writers detect a live daemon and refuse to race
		// the rollover tick. Failing to write it means that gate is
		// silently disabled, so we treat it as a startup error.
		if err := tdns.WriteRolloverDaemonSentinel(conf.Internal.KeyDB); err != nil {
			tdns.Shutdowner(conf, fmt.Sprintf("error writing rollover daemon sentinel: %v", err))
		}
		defer tdns.ClearRolloverDaemonSentinel(conf.Internal.KeyDB)
	}

	apirouter, err := conf.SetupAPIRouter(ctx)
	if err != nil {
		tdns.Shutdowner(conf, fmt.Sprintf("Error setting up API router: %v", err))
	}

	// Start application threads
	// SIGHUP reload watcher
	hup := make(chan os.Signal, 1)
	signal.Notify(hup, syscall.SIGHUP)
	defer signal.Stop(hup)
	go func() {
		for {
			select {
			case <-ctx.Done():
				return
			case <-hup:
				if _, err := conf.ReloadZoneConfig(ctx); err != nil {
					log.Printf("SIGHUP reload failed: %v", err)
				}
			}
		}
	}()

	err = conf.StartAuth(ctx, apirouter)
	if err != nil {
		tdns.Shutdowner(conf, fmt.Sprintf("Error starting TDNS threads: %v", err))
	}

	// Enter main loop
	conf.MainLoop(ctx, stop)
}
