package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// libEnv holds the environment a library's -env.sh script exports on a
// successful detection (the `export NAME="value"` lines from stdout).
type libEnv struct {
	group string
	vars  map[string]string
}

// envScriptRel maps a registry Group value to the -env.sh path relative
// to the dnssec-algorithms repo root.
var envScriptRel = map[string]string{
	"liboqs":  "liboqs/liboqs-env.sh",
	"sqisign": "sqisignc/sqisign-env.sh",
	"qruov":   "qruovc/qruov-env.sh",
}

// detectLib runs the group's -env.sh script (via bash) from algrepo. On
// success (exit 0, non-empty stdout) it parses the exported variables
// and returns them. A non-zero exit or missing script is an error — the
// caller turns that into a hard "library not available" failure.
func detectLib(algrepo, group string) (libEnv, error) {
	rel, ok := envScriptRel[group]
	if !ok {
		return libEnv{}, fmt.Errorf("no -env.sh known for group %q", group)
	}
	script := filepath.Join(algrepo, rel)
	vlog("detecting %s: running %s", group, script)
	if _, err := os.Stat(script); err != nil {
		return libEnv{}, fmt.Errorf("detection script %s not found", script)
	}

	// The scripts print `export NAME="value"` to stdout on success,
	// diagnostics to stderr, and exit non-zero when the lib is absent.
	// They use ${BASH_SOURCE[0]} so must run under bash, not sh.
	cmd := exec.Command("bash", script)
	cmd.Dir = algrepo
	var stdout, stderr strings.Builder
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	if err != nil {
		msg := strings.TrimSpace(stderr.String())
		if msg == "" {
			msg = err.Error()
		}
		return libEnv{}, fmt.Errorf("%s", firstLine(msg))
	}
	vars := parseExports(stdout.String())
	if len(vars) == 0 {
		// Exit 0 but nothing exported — treat as not-detected to be safe.
		return libEnv{}, fmt.Errorf("detection produced no environment (%s)", firstLine(stderr.String()))
	}
	for _, n := range sortedKeys(vars) {
		vlog("    %s=%s", n, vars[n])
	}
	return libEnv{group: group, vars: vars}, nil
}

// sortedKeys returns the keys of m in sorted order, for deterministic
// verbose output.
func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// parseExports pulls `export NAME="value"` (or NAME=value) lines out of
// the script's stdout.
func parseExports(out string) map[string]string {
	vars := map[string]string{}
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		line = strings.TrimPrefix(line, "export ")
		eq := strings.IndexByte(line, '=')
		if eq <= 0 {
			continue
		}
		name := strings.TrimSpace(line[:eq])
		val := strings.TrimSpace(line[eq+1:])
		val = strings.Trim(val, `"'`)
		if name == "" || val == "" {
			continue
		}
		vars[name] = val
	}
	return vars
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}

// genEnvMk builds the Makefile fragment the app includes. It records the
// dnssec-algorithms checkout path (ALGREPO) so the app Makefile can re-run
// genalgs itself when algs.list changes, and merges the per-library
// environments: PKG_CONFIG_PATH entries are joined, other variables
// (CGO_LDFLAGS, LD_LIBRARY_PATH) are collected. Variables are exported so
// they reach the `go build` subprocess.
func genEnvMk(algrepo string, needGroups map[string]bool, envByGroup map[string]libEnv) []byte {
	var b strings.Builder
	b.WriteString("# Code generated by genalgs; DO NOT EDIT.\n")
	b.WriteString("# Build environment for the C-backed algorithms this app links.\n")
	b.WriteString("# Included by the app Makefile so cgo/pkg-config can find the\n")
	b.WriteString("# libraries, and so make can re-run genalgs when algs.list changes.\n\n")

	// ALGREPO lets the app Makefile re-run genalgs without the user
	// re-supplying --algrepo. Recorded on every generate, whether or not
	// any C-backed library is needed.
	fmt.Fprintf(&b, "ALGREPO := %s\n\n", algrepo)

	if len(needGroups) == 0 {
		b.WriteString("# (no C-backed algorithms selected; no library env to set)\n")
		return []byte(b.String())
	}

	// Collect, joining PKG_CONFIG_PATH across libraries and unioning the rest.
	pkgPaths := []string{}
	others := map[string][]string{}
	for _, g := range sortedGroups(needGroups) {
		env := envByGroup[g]
		names := make([]string, 0, len(env.vars))
		for n := range env.vars {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			v := env.vars[n]
			if n == "PKG_CONFIG_PATH" {
				pkgPaths = append(pkgPaths, v)
			} else {
				others[n] = appendUnique(others[n], v)
			}
		}
	}

	if len(pkgPaths) > 0 {
		fmt.Fprintf(&b, "export PKG_CONFIG_PATH := %s$(if $(PKG_CONFIG_PATH),:$(PKG_CONFIG_PATH))\n",
			strings.Join(pkgPaths, ":"))
	}
	otherNames := make([]string, 0, len(others))
	for n := range others {
		otherNames = append(otherNames, n)
	}
	sort.Strings(otherNames)
	for _, n := range otherNames {
		// Path-list variables must be colon-joined (":") — space-joining
		// several LD_LIBRARY_PATH values would produce an invalid path like
		// "/a /b". Flag-style variables (CGO_LDFLAGS) are space-joined.
		sep := " "
		if isPathListVar(n) {
			sep = ":"
		}
		fmt.Fprintf(&b, "export %s := %s\n", n, strings.Join(others[n], sep))
	}
	return []byte(b.String())
}

// isPathListVar reports whether an environment variable holds a
// colon-separated list of paths (rather than a space-separated flag list).
func isPathListVar(name string) bool {
	switch name {
	case "LD_LIBRARY_PATH", "DYLD_LIBRARY_PATH", "PKG_CONFIG_PATH":
		return true
	}
	return false
}

func appendUnique(xs []string, v string) []string {
	for _, x := range xs {
		if x == v {
			return xs
		}
	}
	return append(xs, v)
}
