// Command genalgs generates the per-application algorithm registration
// files for a tdns app from two inputs:
//
//  1. the authoritative metadata table in
//     github.com/johanix/dnssec-algorithms/registry (all algorithms), and
//  2. a per-app plain-text "algs.list" (one algorithm NAME per line) that
//     selects which algorithms this app links an *implementation* for.
//
// It writes into the app's directory:
//
//   - metadata_gen.go: RegisterMetadata(...) for EVERY algorithm in the
//     registry. Pure Go, no build tags, compiled into every app — this is
//     the global codepoint↔name↔role table that lets name-aware UI (e.g.
//     dog +algchase) recognize any codepoint, even one it cannot verify.
//
//   - impl_<group>_gen.go: for each build-tag group (liboqs, sqisign,
//     qruov) that the app's algs.list selects, a //go:build <group> file
//     with Register(...) calls that wire the real implementation into
//     miekg/dns. PureGo-group algorithms have no build tag and go into
//     impl_purego_gen.go.
//
// Register on a codepoint that already has a metadata entry PROMOTES it
// to a real (usable) algorithm — see v2/algorithms record().
//
// Usage:
//
//	genalgs -list <algs.list> -out <dir> [-pkg main]
//
// Typically invoked via `go generate` from each app.
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/johanix/dnssec-algorithms/registry"
)

func main() {
	listPath := flag.String("list", "algs.list", "path to the per-app algorithm list (one NAME per line)")
	outDir := flag.String("out", ".", "directory to write the generated files into")
	pkgName := flag.String("pkg", "main", "package name for the generated files")
	flag.Parse()

	if err := run(*listPath, *outDir, *pkgName); err != nil {
		fmt.Fprintf(os.Stderr, "genalgs: %v\n", err)
		os.Exit(1)
	}
}

func run(listPath, outDir, pkgName string) error {
	byName := map[string]registry.Alg{}
	for _, a := range registry.Algorithms {
		byName[a.Name] = a
	}

	selected, err := readList(listPath, byName)
	if err != nil {
		return err
	}

	// 1. metadata_gen.go — every algorithm, always.
	if err := writeFormatted(filepath.Join(outDir, "metadata_gen.go"),
		genMetadata(pkgName, registry.Algorithms)); err != nil {
		return err
	}

	// 2. impl_<group>_gen.go — one per group actually selected by this app.
	byGroup := map[registry.Group][]registry.Alg{}
	for _, a := range selected {
		byGroup[a.Group] = append(byGroup[a.Group], a)
	}
	groups := make([]registry.Group, 0, len(byGroup))
	for g := range byGroup {
		groups = append(groups, g)
	}
	sort.Slice(groups, func(i, j int) bool { return groups[i] < groups[j] })

	for _, g := range groups {
		algs := byGroup[g]
		sort.Slice(algs, func(i, j int) bool { return algs[i].Codepoint < algs[j].Codepoint })
		fname := filepath.Join(outDir, fmt.Sprintf("impl_%s_gen.go", g))
		if err := writeFormatted(fname, genImpl(pkgName, g, algs)); err != nil {
			return err
		}
	}

	fmt.Printf("genalgs: wrote metadata (%d algs) + impl for groups %v into %s\n",
		len(registry.Algorithms), groups, outDir)
	return nil
}

// readList parses the per-app list of algorithm NAMEs, resolving each
// against the registry. Blank lines and #-comments are ignored. An
// unknown name is a hard error — a typo must not silently drop an
// algorithm.
func readList(path string, byName map[string]registry.Alg) ([]registry.Alg, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}
	defer f.Close()

	var out []registry.Alg
	seen := map[string]bool{}
	sc := bufio.NewScanner(f)
	line := 0
	for sc.Scan() {
		line++
		s := strings.TrimSpace(sc.Text())
		if s == "" || strings.HasPrefix(s, "#") {
			continue
		}
		a, ok := byName[s]
		if !ok {
			return nil, fmt.Errorf("%s:%d: unknown algorithm %q (not in the registry)", path, line, s)
		}
		if seen[s] {
			return nil, fmt.Errorf("%s:%d: duplicate algorithm %q", path, line, s)
		}
		seen[s] = true
		out = append(out, a)
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}
	return out, nil
}

const doNotEdit = "// Code generated by genalgs; DO NOT EDIT.\n"

func capsLiteral(c registry.Caps) string {
	return fmt.Sprintf("algs.Capabilities{ForSIG0: %t, ForDNSSEC: %t, ForKSK: %t, ForZSK: %t}",
		c.ForSIG0, c.ForDNSSEC, c.ForKSK, c.ForZSK)
}

func genMetadata(pkgName string, algs []registry.Alg) []byte {
	sorted := append([]registry.Alg(nil), algs...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Codepoint < sorted[j].Codepoint })

	var b bytes.Buffer
	b.WriteString(doNotEdit)
	b.WriteString("//\n// Metadata for every algorithm in the registry, compiled into every\n")
	b.WriteString("// build regardless of which implementations are linked. Register (in the\n")
	b.WriteString("// build-tag-gated impl_*_gen.go files) later promotes an entry to a real,\n")
	b.WriteString("// usable algorithm when its implementation is present.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkgName)
	b.WriteString("import algs \"github.com/johanix/tdns/v2/algorithms\"\n\n")
	b.WriteString("func init() {\n")
	for _, a := range sorted {
		fmt.Fprintf(&b, "\talgs.RegisterMetadata(%d, %q, %s)\n", a.Codepoint, a.Name, capsLiteral(a.Caps))
	}
	b.WriteString("}\n")
	return b.Bytes()
}

func genImpl(pkgName string, group registry.Group, algs []registry.Alg) []byte {
	var b bytes.Buffer
	b.WriteString(doNotEdit)
	if group != registry.PureGo {
		fmt.Fprintf(&b, "//go:build %s\n\n", group)
	}
	fmt.Fprintf(&b, "// Register the %s-group algorithm implementations selected by this app's\n", group)
	b.WriteString("// algs.list. Each Register call promotes the algorithm's metadata entry to a\n")
	b.WriteString("// real, usable algorithm and wires it into miekg/dns.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkgName)

	b.WriteString("import (\n")
	for _, a := range algs {
		fmt.Fprintf(&b, "\t%q\n", a.Package)
	}
	b.WriteString("\n\talgs \"github.com/johanix/tdns/v2/algorithms\"\n")
	b.WriteString(")\n\n")

	b.WriteString("func init() {\n")
	for _, a := range algs {
		pkgIdent := a.Package[strings.LastIndex(a.Package, "/")+1:]
		fmt.Fprintf(&b, "\talgs.Register(%d, %s.New(), %s)\n", a.Codepoint, pkgIdent, capsLiteral(a.Caps))
	}
	b.WriteString("}\n")
	return b.Bytes()
}

func writeFormatted(path string, src []byte) error {
	formatted, err := format.Source(src)
	if err != nil {
		// Write the unformatted source alongside for debugging, then fail.
		_ = os.WriteFile(path+".broken", src, 0o644)
		return fmt.Errorf("gofmt %s: %w (unformatted source written to %s.broken)", path, err, path)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}
