/*
 * Copyright (c) Johan Stenstam, johani@johani.org
 */
package main

import (
	"context"
	"os"
	"os/signal"
	"syscall"

	tdns "github.com/johanix/tdns/v2"
	_ "github.com/johanix/tdns/v2/core" // Import for RR type registration
)

// tdns-ncli is tdns-cli plus the ability to address SEVERAL instances of the
// same daemon, one command tree per instance, configured in tdns-cli.yaml.
// It ships alongside tdns-cli rather than replacing it so both can be run in
// parallel while the behaviour and the documentation settle.
// See docs/2026-09-07-cli-multi-instance-design.md.

// Algorithm metadata is generated by genalgs (see algs.list): metadata for
// every registry algorithm, no real implementations -- pure-Go, no liboqs.

// initGlobals identifies this binary to the tdns library. App.Type is
// load-bearing: left unset it is the zero value, which is no AppType at all,
// and every check keyed on AppTypeCli takes the wrong branch.
func initGlobals() {
	tdns.Globals.App.Name = appName
	tdns.Globals.App.Version = appVersion
	tdns.Globals.App.Date = appDate
	tdns.Globals.App.Type = tdns.AppTypeCli
}

func main() {
	initGlobals()

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	ExecuteContext(ctx)
}
