/*
 * Copyright (c) Johan Stenstam, johani@johani.org
 */
package main

import (
	"context"
	"os"
	"os/signal"
	"syscall"

	tdns "github.com/johanix/tdns/v2"
)

// dog validates RRSIGs across the full algorithm range, so it links real
// implementations for every algorithm in its algs.list (the full set) —
// including the C-backed ones, which is why dog now builds CGO_ENABLED=1.
// Algorithm registration is generated by genalgs: metadata_algs.go
// registers name/codepoint/role for EVERY registry algorithm (so
// sigchase/+algchase can name any algorithm), and registered_algs.go
// registers a real implementation for each selected algorithm. Run
// tdns-genalgs --algrepo=<dir> before building; the generated files are
// build artifacts (gitignored).

func main() {
	tdns.Globals.App.Name = appName
	tdns.Globals.App.Version = appVersion
	tdns.Globals.App.Date = appDate

	// Create root context with signal handling
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	ExecuteContext(ctx)
}
