/*
 * Copyright (c) 2024 Johan Stenstam, johan.stenstam@internetstiftelsen.se
 */
package main

import (
	"context"
	"os"
	"os/signal"
	"syscall"

	tdns "github.com/johanix/tdns/v2"
)

// Algorithm registration is generated by genalgs (see algs.list): the
// generated metadata_algs.go registers metadata for every registry
// algorithm, and registered_algs.go registers a real implementation for
// each algorithm this app selected. Run tdns-genalgs --algrepo=<dir>
// before building; the generated files are build artifacts (gitignored).

func main() {
	tdns.Globals.App.Type = tdns.AppTypeImr
	tdns.Globals.App.Name = appName
	tdns.Globals.App.Version = appVersion
	tdns.Globals.App.Date = appDate

	// Create root context with signal handling
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	ExecuteContext(ctx)
}
